---
state: present

kube_system_namespace: kube-system
broker_name: template-service-broker
broker_namespace: openshift-template-service-broker
broker_image: docker.io/openshift/origin-template-service-broker:latest
broker_log_level: '0'
broker_node_selector: ""

apiserver_serviceaccount_name: apiserver
apiserver_service_name: apiserver
apiserver_serving_cert_secret : apiserver-serving-cert

template_namespaces: ['openshift']
